### ISSUE TITLE
Would a published sobol crate be useful to you?

### ISSUE THREAD

**Issue by cessen** [64/iris#1]
Hi there!  I'm really pleased that you're using my sobol sampling code in your renderer.  And it's making me wonder if I shouldn't clean it up and publish it as a crate.  Would that be useful to you?

Part of why I'm asking is that your version is already outdated, and is using an Owen scrambling hash that I now know has problems.  The latest version in Psychopath has a fixed (and much higher quality) version.  I've been teetering on the edge of making it a properly published crate, but I keep making excuses not to, ha ha.

**Comment by 64** [comment]
Yes, it would be very useful! I haven't worked on this project in a while, but it would be very useful if you published it.

**Comment by cessen** [comment]
Here you go: https://crates.io/crates/sobol_burley

If there's anything that would make the crate easier for you to use, please don't hesitate to file an issue!  PRs are also more than welcome, of course.
